[INFO   ] Logger: Record log in /Users/m-takeuchi/research/kyoto-u/exp_data/ILIS/ILIS_program_t-i/ilislife/logs/darwin_kivy_16-07-25_54.txt
[INFO   ] Factory: 193 symbols loaded
[DEBUG  ] Cache: register <kv.image> with limit=None, timeout=60
[DEBUG  ] Cache: register <kv.atlas> with limit=None, timeout=None
[INFO   ] Image: Providers: img_tex, img_imageio, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[DEBUG  ] Cache: register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] Cache: register <kv.shader> with limit=1000, timeout=3600
[DEBUG  ] Cache: register <kv.lang> with limit=None, timeout=None
[INFO   ] Text: Provider: sdl2
[DEBUG  ] Cache: register <textinput.label> with limit=None, timeout=60.0
[DEBUG  ] Cache: register <textinput.width> with limit=None, timeout=60.0
[DEBUG  ] App: Loading kv <./ilislife.kv>
[INFO   ] OSC: using <multiprocessing> for socket
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: OpenGL version <b'2.1 INTEL-10.14.66'>
[INFO   ] GL: OpenGL vendor <b'Intel Inc.'>
[INFO   ] GL: OpenGL renderer <b'Intel Iris OpenGL Engine'>
[INFO   ] GL: OpenGL parsed version: 2, 1
[INFO   ] GL: Shading version <b'1.20'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <16>
[DEBUG  ] Shader: Fragment compiled successfully
[DEBUG  ] Shader: Vertex compiled successfully
[DEBUG  ] ImageImageIO: Load </Users/m-takeuchi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/data/glsl/default.png>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[DEBUG  ] Atlas: Load </Users/m-takeuchi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/data/../data/images/defaulttheme.atlas>
[DEBUG  ] Atlas: Need to load 1 images
[DEBUG  ] Atlas: Load </Users/m-takeuchi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/data/../data/images/defaulttheme-0.png>
[DEBUG  ] ImageImageIO: Load </Users/m-takeuchi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/data/../data/images/defaulttheme-0.png>
[DEBUG  ] Resource: add </Library/Fonts> in path list
[DEBUG  ] Resource: add </Library/Fonts/Microsoft> in path list
[DEBUG  ] Resource: add </System/Library/Fonts> in path list
[DEBUG  ] Resource: add </Users/m-takeuchi/Library/Fonts> in path list
[DEBUG  ] Resource: add </Users/m-takeuchi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/data/fonts> in path list
[INFO   ] GL: NPOT texture support is available
[DEBUG  ] Base: Create provider from mouse
[INFO   ] Base: Start application main loop
[INFO   ] Base: Leaving application in progress...
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "main.py", line 542, in <module>
[WARNING] stderr:     IlislifeApp().run()
[WARNING] stderr:   File "/Users/m-takeuchi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/app.py", line 828, in run
[WARNING] stderr:     runTouchApp()
[WARNING] stderr:   File "/Users/m-takeuchi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/base.py", line 487, in runTouchApp
[WARNING] stderr:     EventLoop.window.mainloop()
[WARNING] stderr:   File "/Users/m-takeuchi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/core/window/window_sdl2.py", line 637, in mainloop
[WARNING] stderr:     self._mainloop()
[WARNING] stderr:   File "/Users/m-takeuchi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/core/window/window_sdl2.py", line 390, in _mainloop
[WARNING] stderr:     EventLoop.idle()
[WARNING] stderr:   File "/Users/m-takeuchi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/base.py", line 327, in idle
[WARNING] stderr:     Clock.tick()
[WARNING] stderr:   File "/Users/m-takeuchi/.pyenv/versions/3.4.3/lib/python3.4/site-packages/kivy/clock.py", line 412, in tick
[WARNING] stderr:     self._process_events()
[WARNING] stderr:   File "kivy/_clock.pyx", line 329, in kivy._clock.CyClockBase._process_events (/var/folders/hj/v3sdjs454rb_9gwwlp9j3p4c0000gn/T/pip-keicfvdj-build/kivy/_clock.c:6591)
[WARNING] stderr:   File "kivy/_clock.pyx", line 359, in kivy._clock.CyClockBase._process_events (/var/folders/hj/v3sdjs454rb_9gwwlp9j3p4c0000gn/T/pip-keicfvdj-build/kivy/_clock.c:6471)
[WARNING] stderr:   File "kivy/_clock.pyx", line 357, in kivy._clock.CyClockBase._process_events (/var/folders/hj/v3sdjs454rb_9gwwlp9j3p4c0000gn/T/pip-keicfvdj-build/kivy/_clock.c:6393)
[WARNING] stderr:   File "kivy/_clock.pyx", line 164, in kivy._clock.ClockEvent.tick (/var/folders/hj/v3sdjs454rb_9gwwlp9j3p4c0000gn/T/pip-keicfvdj-build/kivy/_clock.c:2979)
[WARNING] stderr:   File "main.py", line 472, in get_mydata
[WARNING] stderr:     self.to_val = val = GetValue.make_random_data()
[WARNING] stderr: NameError: name 'GetValue' is not defined
